version: '3.4'
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    command: npm run dev
    ports:
      - 8000:8000
    volumes:
      - .:/src/
      - nodemodules:/src/node_modules

volumes:
  nodemodules: {}
